service:
  name: hour-tracker-v2

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    DYNAMODB_TABLE_USERS: Users-dev-hour-tracker-v2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:eu-central-1:423343990083:table/Users-dev-hour-tracker-v2'
        - 'arn:aws:dynamodb:eu-central-1:423343990083:table/Users-dev-hour-tracker-v2/index/*'

functions:
  getUsers:
    handler: users/handler.handler
    events:
      - http:
          path: /users
          method: GET
          cors: true

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: Users-${self:provider.stage}-${self:service.name}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: "S"
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
