service:
  name: hour-tracker-v2

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    DYNAMODB_TABLE_USERS: Users-${self:provider.stage}-${self:service.name}
    DYNAMODB_TABLE_USERS_ARN: arn:aws:dynamodb:${self:provider.region}:423343990083:table/Users-${self:provider.stage}-${self:service.name}
    DYNAMODB_TABLE_HOURS: Hours-${self:provider.stage}-${self:service.name}
    DYNAMODB_TABLE_HOURS_ARN: arn:aws:dynamodb:${self:provider.region}:423343990083:table/Hours-${self:provider.stage}-${self:service.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - '${self:provider.environment.DYNAMODB_TABLE_USERS_ARN}'
        - '${self:provider.environment.DYNAMODB_TABLE_USERS_ARN}/index/*'
        - '${self:provider.environment.DYNAMODB_TABLE_HOURS_ARN}'
        - '${self:provider.environment.DYNAMODB_TABLE_HOURS_ARN}/index/*'

functions:
  getUsers:
    handler: users/handler.handler
    events:
      - http:
          path: /users
          method: GET
          cors: true

  getHours:
    handler: hours/get-handler.handler
    events:
      - http:
          path: /hours
          method: GET
          cors: true

  getHour:
    handler: hours/get-one-handler.handler
    events:
      - http:
          path: /hours/{id}
          method: GET
          cors: true

  updateHour:
    handler: hours/put-handler.handler
    events:
      - http:
          path: /hours/{id}
          method: PUT
          cors: true

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: Users-${self:provider.stage}-${self:service.name}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: "S"
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    Hours:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: Hours-${self:provider.stage}-${self:service.name}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: "S"
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
